# Ansible playbook to install the required packages on the master and worker nodes
- hosts: "master, workers"
  become: yes # Run as root
  remote_user: smaniak  # Specify the user for SSH

  tasks:
    - name: Configure containerd
      shell: |
        sudo tee /etc/modules-load.d/containerd.conf <<EOF
        overlay
        br_netfilter
        EOF
        sudo modprobe overlay
        sudo modprobe br_netfilter
    - name: Configure kernel
      shell: |
        sudo tee /etc/sysctl.d/kubernetes.conf <<EOF
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1
        EOF
    - name: Apply changes
      shell: sudo sysctl --system
    - name: Install containerd dependencies
      apt:
        name: [ 'apt-transport-https','ca-certificates','curl','gnupg-agent','software-properties-common' ]
        state: present
        update_cache: yes
    - name: Add containerd gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add containerd software repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present
        filename: docker.list
        update_cache: yes
    - name: Install containerd
      apt:
        name: [ 'containerd.io' ]
        state: present
        update_cache: yes
    - name: Configure containerd
      shell: |
        sudo mkdir -p /etc/containerd
        sudo containerd config default | sudo tee /etc/containerd/config.toml
        sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
    - name: Restart and enable containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes
    - name: Disable swap
      shell: swapoff -a
    - name: Stop swap from mounting
      shell: sed -i 's/^\/swap/#\/swap/g' /etc/fstab
    - name: Install dependencies
      apt:
        name: [ 'apt-transport-https','ca-certificates','curl','gnupg-agent','software-properties-common' ]
        state: present
        update_cache: yes
    - name: Add Kubernetes gpg key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: Add Kubernetes software repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list
        update_cache: yes
    - name: Install kubernetes
      apt:
        name: [ 'kubelet','kubeadm','kubectl' ]
        state: present
        update_cache: yes
    - name: Hold kubelet package at current version
      ansible.builtin.dpkg_selections:
        name: 'kubelet'
        selection: hold
    - name: Hold kubeadm package at current version
      ansible.builtin.dpkg_selections:
        name: 'kubeadm'
        selection: hold
    - name: Hold kubectl package at current version
      ansible.builtin.dpkg_selections:
        name: 'kubectl'
        selection: hold
    # Setup isci for Longhorn
    - name: Install iscsi and nfs-common
      apt:
        name: [ 'open-iscsi', 'nfs-common' ]
        state: present
        update_cache: yes
